[package]
name = "english"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.15"
inkwell = { version = "0.7", features = ["llvm21-1"] }
thiserror = "2.0"

[[bin]]
name = "englishc"
path = "src/main.rs"
